jenkins:
  #enforce login/set admin username/password
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  #set default permissions for admin/authenticated users
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Administer:admin"
        - "GROUP:Overall/Read:anonymous"
  #enable agent/controller login
  remotingSecurity:
    enabled: true
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    installations:
    - home: "/usr/lib/jvm/java-17-openjdk-amd64/"
      name: "J17"
  maven:
    installations:
    - name: "M3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.9.3"
security:
  #run builds as user that executed the job
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  #set default URL
  location:
    url: http://127.0.0.1:8080/

jobs:
  - file: /usr/local/seedjob.groovy
